DROP TABLE IF EXISTS Comments;

CREATE TABLE IF NOT EXISTS Comments(
id INT AUTO_INCREMENT,
post_id INT NOT NULL,
author VARCHAR(255) NOT NULL,
body TEXT NOT NULL,
timestamp DATETIME NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (post) REFERENCES Posts(id) ON DELETE CASCADE,
FOREIGN KEY (sender) REFERENCES Users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

DELIMITER //
CREATE TRIGGER CreateCommentNotification
    AFTER INSERT ON Comments
    FOR EACH ROW
    BEGIN
        INSERT INTO Notifications (id, type, status) VALUES (NEW.id, 'comment', 'unread');
		END; //
DELIMITER ;

INSERT INTO Comments (id, post_id, author, body, timestamp)
VALUES
(159, 92, "EmeraldDragonfly", "Cette citation d'Albert Einstein est un rappel important que l'échec est souvent une étape nécessaire sur le chemin de l'innovation.", '2023-01-03 00:31:47'),
(119, 159, "BlissfulGnome","J'aime cette citation parce qu'elle montre que le succès ne vient pas toujours facilement, mais qu'il est souvent précédé de nombreux échecs.", '2023-02-23 19:47:07'),
(8, 15, "SapphireJazz", "C'est tellement vrai - si vous n'essayez jamais quelque chose de nouveau, vous ne pouvez jamais savoir si cela fonctionnera ou non.", '2023-01-13 20:23:38'),
(15, 16, "MysticWombat", "Cette citation est une excellente source de motivation pour continuer à essayer, même lorsque les choses deviennent difficiles.", '2023-03-16 16:52:17'),
(16, 40, "ElectricPenguin", "L'innovation est souvent le résultat de l'échec - cette citation d'Albert Einstein nous rappelle que cela fait partie du processus.", '2023-02-25 17:36:58'),
(31, 40, "CosmicChameleon", "Je suis d'accord avec cette citation - l'échec est simplement une opportunité d'apprendre et de grandir.", '2023-02-27 20:09:14'),
(40, 8, "VelvetPhoenix", "Cela nous rappelle que l'innovation est souvent le résultat de la persévérance et de la détermination à surmonter les obstacles.", '2023-03-17 04:14:47'),
(50, 40, "RadiantLynx", "J'aime cette citation parce qu'elle nous rappelle que même les plus grands esprits ont connu des échecs - c'est normal et cela fait partie de la vie.", '2023-02-15 10:11:20'),
(54, 159, "LunarSphinx", "C'est une citation très inspirante qui encourage les gens à sortir de leur zone de confort et à prendre des risques.", '2023-02-22 19:02:51'),
(56, 98, "GalacticSailor", "Les personnes qui ont peur de l'échec ont souvent du mal à innover - cette citation est un rappel que l'échec est une étape importante pour progresser.", '2023-02-15 06:28:57'),
(72, 54, "CrimsonCobra", "L'échec est souvent considéré comme une mauvaise chose, mais cette citation nous rappelle que c'est en fait une étape importante vers le succès.", '2023-03-02 23:38:25'),
(92, 54, "CelestialRaven", "Je suis d'accord avec Einstein - l'innovation nécessite souvent des essais et des erreurs, et il n'y a rien de mal à cela.", '2023-04-01 14:12:24'),
(98, 54, "SilverStallion", "Cette citation est une excellente source de motivation pour continuer à essayer, même lorsque les choses ne fonctionnent pas comme prévu.", '2023-03-15 23:37:43'),
(105, 54, "EnigmaticKraken", "Cela nous rappelle que même les personnes les plus intelligentes et les plus talentueuses ont connu des échecs - personne n'est parfait.", '2023-01-13 17:58:54'),
(161, 92, "MysticMoose", "J'aime cette citation parce qu'elle montre que l'échec est souvent une étape nécessaire pour atteindre le succès.", '2023-01-17 06:26:33'),
(172, 92, "FieryFalcon", "L'échec est souvent décourageant, mais cette citation est un rappel que c'est une partie normale du processus d'innovation.", '2023-01-23 09:47:23'),
(191, 92, "OceanicOctopus", "Cette citation est un excellent rappel que nous devons accepter l'échec comme faisant partie du voyage vers le succès.", '2023-02-23 19:01:01'),
(196, 92, "CrimsonCheetah", "Cela nous rappelle que l'innovation nécessite souvent des essais et des erreurs - c'est normal et cela fait partie du processus.", '2023-01-15 16:10:31'),
(205, 92, "CosmicCactus", "J'aime cette citation parce qu'elle encourage les gens à sortir de leur zone de confort et à prendre des risques.", '2023-03-31 08:01:02'),
(224, 92, "EnchantedElk", "L'échec est souvent difficile à accepter, mais cette citation est un rappel que c'est une étape importante pour apprendre et grandir.", '2023-02-14 00:10:51'),
(239, 92, "RadiantRaccoon", "Cette citation est une excellente source de motivation pour continuer à essayer, même lorsque les choses deviennent difficiles.", '2023-01-18 03:47:33'),
(410, 205, "EmeraldDragonfly", "Cette citation est une belle leçon de vie qui nous rappelle que l'échec n'est pas une fin en soi, mais une opportunité de rebondir et de faire mieux la prochaine fois.", '2023-03-25 09:54:39'),
(245, 92, "JadeJaguar", "J'aime cette citation car elle encourage à ne pas avoir peur de l'échec et à continuer à persévérer malgré les difficultés rencontrées.", '2023-03-22 20:31:03'),
(267, 92, "StarrySwan", "C'est une citation inspirante qui montre que l'innovation est le fruit du travail, de la détermination et du courage de sortir de sa zone de confort.", '2023-04-07 09:20:54'),
(272, 105, "ElectricEagle", "L'échec peut sembler effrayant, mais cette citation nous rappelle que c'est une étape nécessaire pour atteindre de nouveaux sommets et réaliser des choses incroyables.", '2023-02-04 10:03:55'),
(276, 300, "FieryFox", "C'est une citation qui encourage les gens à prendre des risques et à sortir de leur zone de confort pour réaliser leur potentiel le plus élevé.", '2023-01-24 07:48:42'),
(277, 300, "BlissfulGnome", "L'échec est souvent considéré comme un obstacle à surmonter, mais cette citation nous rappelle que c'est une étape incontournable pour atteindre le succès.", '2023-03-20 01:14:00'),
(280, 300, "SapphireJazz", "Cette citation est une belle source de motivation pour continuer à persévérer et à travailler dur, même lorsque les choses ne fonctionnent pas comme prévu.", '2023-02-09 09:22:09'),
(295, 300, "MysticWombat", "Cela nous rappelle que chaque échec est une opportunité de grandir et d'apprendre quelque chose de nouveau, qui peut nous aider à réussir à l'avenir.", '2023-01-18 16:55:40'),
(298, 300, "ElectricPenguin", "L'échec est un élément inévitable de tout processus d'innovation, et cette citation nous encourage à embrasser cette réalité plutôt que de la craindre.", '2023-03-13 08:22:47'),
(300, 377, "CosmicChameleon", "Cette citation nous rappelle que l'échec est simplement une étape sur le chemin du succès, et que chaque échec nous rapproche un peu plus de notre objectif.", '2023-02-04 12:04:44'),
(305, 377, "VelvetPhoenix", "J'aime cette citation car elle montre que l'innovation est souvent le résultat de la persévérance et de la détermination à surmonter les obstacles.", '2023-02-06 22:04:38'),
(313, 377, "RadiantLynx", "Cette citation nous encourage à ne pas avoir peur de l'échec et à continuer à essayer jusqu'à ce que nous réussissions.", '2023-03-16 21:35:50'),
(314, 377, "LunarSphinx", "L'échec est une opportunité de réévaluer notre approche et de trouver de nouvelles façons de progresser, et cette citation nous rappelle de garder cela à l'esprit lorsque nous sommes confrontés à des défis.", '2023-03-14 06:41:52'),
(325, 377, "GalacticSailor", "Cette citation est une belle leçon de vie qui nous rappelle que nous devons apprendre à embrasser l'échec comme faisant partie du voyage vers le succès.", '2023-03-05 14:03:55'),
(377, 205, "CrimsonCobra", "J'aime cette citation car elle nous encourage à sortir de notre zone de confort et à essayer de nouvelles choses, même si cela implique de prendre des risques.", '2023-03-21 14:32:46'),
(382, 205, "CelestialRaven", "Cette citation nous rappelle que l'échec est simplement une étape sur le chemin de l'innovation, et que chaque échec nous rapproche un peu plus de notre objectif.", '2023-03-20 02:54:25'),
(388, 205, "SilverStallion", "L'échec peut sembler décourageant, mais cette citation nous encourage à continuer à essayer jusqu'à ce que nous réussissions.", '2023-04-03 08:09:45'),
(396, 205, "EnigmaticKraken", "Cette citation est une belle source de motivation pour continuer à persévérer et à travailler dur, même lorsque nous sommes confrontés à des obstacles apparemment insurmontables.", '2023-03-13 08:45:55'),
(658, 717, "EmeraldDragonfly", "Cette citation nous rappelle que l'échec n'est pas une indication de notre valeur personnelle, mais simplement une expérience qui peut nous aider à grandir et à évoluer.", '2023-01-18 22:43:02'),
(412, 611, "MysticMoose", "J'aime cette citation car elle nous encourage à sortir de notre zone de confort et à prendre des risques pour atteindre nos objectifs les plus élevés.", '2023-02-08 17:36:23'),
(420, 611, "FieryFalcon", "Cette citation nous rappelle que le chemin vers le succès peut être difficile et semé d'embûches, mais que chaque échec nous rapproche un peu plus de notre but.", '2023-02-03 15:40:18'),
(425, 611, "OceanicOctopus", "L'échec peut nous faire douter de nous-mêmes, mais cette citation nous encourage à persévérer et à continuer à travailler dur pour atteindre nos objectifs.", '2023-02-28 12:14:29'),
(431, 611, "CrimsonCheetah", "Cette citation nous rappelle que l'innovation et le progrès ne sont possibles que si nous sommes prêts à prendre des risques et à surmonter les échecs.", '2023-03-10 13:49:26'),
(444, 611, "CosmicCactus", "J'aime cette citation car elle montre que l'échec peut être un catalyseur pour la croissance personnelle et la réussite à long terme.", '2023-02-08 16:43:29'),
(458, 616, "EnchantedElk", "Cette citation nous rappelle que chaque échec est une opportunité d'apprendre quelque chose de nouveau qui peut nous aider à réussir dans l'avenir.", '2023-01-07 21:44:17'),
(468, 616, "RadiantRaccoon", "L'échec peut être décourageant, mais cette citation nous encourage à ne pas abandonner et à continuer à persévérer jusqu'à ce que nous atteignions notre but.", '2023-01-15 03:58:59'),
(485, 616, "JadeJaguar", "Cette citation est une belle source de motivation pour surmonter les défis et les obstacles qui se dressent sur notre chemin vers le succès.", '2023-03-29 21:01:17'),
(486, 616, "StarrySwan", "Cette citation nous rappelle que l'échec est un élément naturel de tout processus créatif et que chaque échec peut nous rapprocher de notre but ultime.", '2023-01-16 15:09:11'),
(498, 616, "ElectricEagle", "J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à le voir comme une étape nécessaire sur le chemin de la réussite.", '2023-01-08 13:31:44'),
(525, 717, "FieryFox", "Cette citation nous rappelle que le succès n'est pas un événement unique, mais un processus qui implique souvent de nombreux échecs et de nombreuses tentatives.", '2023-01-27 14:43:58'),
(536, 717, "BlissfulGnome", "L'échec peut être difficile à accepter, mais cette citation nous rappelle que c'est une occasion de grandir et de devenir plus fort.", '2023-03-14 05:49:35'),
(540, 717, "SapphireJazz", "Cette citation nous encourage à ne pas avoir peur de l'échec et à continuer à essayer jusqu'à ce que nous réussissions.", '2023-02-08 17:13:45'),
(543, 717, "MysticWombat", "Cette citation nous rappelle que l'échec peut être un moment difficile, mais qu'il peut aussi nous aider à découvrir de nouvelles opportunités et de nouveaux chemins vers le succès.", '2023-03-16 14:36:06'),
(562, 717, "ElectricPenguin", "J'aime cette citation car elle nous encourage à ne pas abandonner nos rêves, même si nous sommes confrontés à des obstacles et à des échecs.", '2023-03-15 07:35:03'),
(573, 717, "CosmicChameleon", "Cette citation nous rappelle que l'innovation et le progrès nécessitent souvent de prendre des risques et de sortir de notre zone de confort.", '2023-02-10 05:52:38'),
(594, 717, "VelvetPhoenix", "L'échec peut sembler décourageant, mais cette citation nous encourage à rester concentrés sur notre objectif et à continuer à travailler dur.", '2023-02-01 09:25:14'),
(595, 717, "RadiantLynx", "Cette citation nous rappelle que l'échec est simplement une étape sur le chemin de la réussite, et que chaque échec nous rapproche un peu plus de notre but.", '2023-02-01 09:27:30'),
(611, 717, "LunarSphinx", "J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à persévérer jusqu'à ce que nous atteignions notre object", '2023-03-28 15:04:50'),
(616, 717, "GalacticSailor","Cette citation nous rappelle que le succès n'est pas une destination finale, mais un voyage qui implique des hauts et des bas.", '2023-02-18 16:21:18'),
(617, 717, "CrimsonCobra","L'échec peut être dévastateur, mais cette citation nous encourage à ne pas perdre espoir et à continuer à avancer malgré les obstacles.", '2023-03-18 21:43:35'),
(637, 717, "CelestialRaven","Cette citation nous encourage à ne pas avoir peur de prendre des risques et à apprendre de nos erreurs pour nous améliorer.", '2023-01-11 18:02:47'),
(638, 717, "SilverStallion","J'aime cette citation car elle nous rappelle que chaque échec peut nous aider à acquérir de nouvelles compétences et à devenir plus compétents.", '2023-03-26 05:33:38'),
(644, 717, "EnigmaticKraken", "Cette citation nous rappelle que même les plus grands leaders ont connu l'échec, mais leur persévérance les a finalement menés à la réussite.", '2023-02-23 18:06:21'),
(659, 498, "MysticMoose","L'échec peut sembler insurmontable, mais cette citation nous encourage à ne pas abandonner et à continuer à essayer.", '2023-03-06 11:56:12'),
(679, 638, "FieryFalcon","Cette citation nous rappelle que l'échec n'est pas un signe de faiblesse, mais une opportunité d'apprendre et de grandir.", '2023-04-04 04:50:09'),
(686, 638, "OceanicOctopus","J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à le voir comme un élément important de notre parcours vers la réussite.", '2023-02-19 19:46:35'),
(691, 638, "CrimsonCheetah","Cette citation nous rappelle que chaque échec peut nous donner la force et la motivation nécessaires pour atteindre notre but final.", '2023-03-10 07:54:15'),
(717, 769, "CosmicCactus","L'échec peut sembler décourageant, mais cette citation nous encourage à persévérer et à continuer à travailler dur pour atteindre nos objectifs.", '2023-02-02 16:56:38'),
(718, 769, "EnchantedElk","Cette citation nous rappelle que le succès est souvent le résultat d'une série d'échecs et de tentatives, mais aussi de persévérance et de détermination.", '2023-03-03 09:32:15'),
(724, 769, "RadiantRaccoon","J'aime cette citation car elle nous rappelle que l'échec peut être une expérience positive si nous sommes prêts à apprendre de nos erreurs.", '2023-03-17 18:24:09'),
(725, 774, "JadeJaguar","Cette citation nous encourage à ne pas avoir peur de l'échec et à continuer à prendre des risques pour atteindre notre but ultime.", '2023-02-07 18:55:49'),
(726, 774, "StarrySwan","L'échec peut sembler décourageant, mais cette citation nous rappelle que c'est une occasion de grandir et de nous améliorer en tant que personnes.", '2023-02-13 11:16:04'),
(731, 774, "ElectricEagle","Cette citation nous rappelle que la réussite ne vient pas facilement, mais qu'elle est le résultat d'un travail acharné et de la persévérance face à l'échec.", '2023-02-19 08:01:26'),
(732, 993, "FieryFox","J'aime cette citation car elle nous encourage à ne pas abandonner face à l'échec, mais plutôt à le voir comme une opportunité de progresser et de nous améliorer.", '2023-02-18 12:48:11'),
(737, 993, "BlissfulGnome","Cette citation nous rappelle que l'échec est un élément naturel de tout processus créatif et que chaque échec peut nous rapprocher un peu plus de notre but ultime.", '2023-03-10 11:24:04'),
(742, 993, "SapphireJazz","L'échec peut sembler décourageant, mais cette citation nous encourage à continuer à travailler dur et à persévérer jusqu'à ce que nous atteignions notre objectif.", '2023-03-17 09:20:11'),
(743, 790, "MysticWombat","Cette citation nous rappelle que l'échec est une occasion de réévaluer nos objectifs et de découvrir de nouvelles opportunités pour réussir.", '2023-03-31 14:48:27'),
(759, 790, "ElectricPenguin", "J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à continuer à persévérer jusqu'à ce que nous atteignions notre but.", '2023-01-25 11:44:08'),
(809, 724, "EmeraldDragonfly", "Cette citation nous rappelle que l'échec ne définit pas notre valeur en tant que personne, mais plutôt notre capacité à rebondir.", '2023-03-14 16:56:52'),
(768, 790, "CosmicChameleon", "L'échec peut sembler décourageant, mais cette citation nous encourage à garder une attitude positive et à continuer à travailler dur pour atteindre nos objectifs.", '2023-03-01 21:02:16'),
(769, 658, "VelvetPhoenix", "Cette citation nous rappelle que chaque échec est une occasion de réfléchir sur nos méthodes et d'essayer de nouvelles approches pour atteindre notre but.", '2023-03-23 06:56:34'),
(773, 658, "RadiantLynx", "J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à continuer à persévérer malgré les obstacles.", '2023-01-20 12:21:19'),
(774, 658, "LunarSphinx", "Cette citation nous rappelle que la réussite n'est pas uniquement basée sur les résultats, mais aussi sur notre processus et notre attitude face à l'échec.", '2023-02-13 21:36:27'),
(790, 773, "GalacticSailor", "L'échec peut sembler insurmontable, mais cette citation nous rappelle que nous avons le pouvoir de choisir notre réponse à l'échec et de continuer à avancer.", '2023-02-28 09:14:25'),
(792, 773, "CrimsonCobra", "Cette citation nous encourage à ne pas se laisser décourager par l'échec et à continuer à travailler dur pour atteindre nos objectifs.", '2023-01-19 16:27:53'),
(796, 773, "CelestialRaven", "J'aime cette citation car elle nous rappelle que l'échec peut être une source de motivation pour continuer à travailler dur et à persévérer.", '2023-01-18 07:03:55'),
(801, 724, "SilverStallion", "Cette citation nous rappelle que chaque échec est une occasion de grandir et de devenir plus fort en tant que personne.", '2023-01-07 06:12:02'),
(804, 724, "EnigmaticKraken", "L'échec peut sembler décourageant, mais cette citation nous encourage à ne pas abandonner et à continuer à avancer malgré les difficultés.", '2023-03-03 07:00:48'),
(810, 940, "MysticMoose", "Cette citation nous rappelle que la persévérance et la détermination sont les clés de la réussite face à l'échec.", '2023-03-25 19:21:27'),
(837, 940, "FieryFalcon", "J'aime cette citation car elle nous encourage à ne pas avoir peur de l'échec et à continuer à essayer jusqu'à ce que nous atteignions notre but.", '2023-02-28 12:46:12'),
(870, 940, "OceanicOctopus", "Cette citation nous rappelle que l'échec peut être un enseignement précieux pour nous aider à prendre des décisions plus avisées à l'avenir.", '2023-02-15 17:54:57'),
(882, 717, "CrimsonCheetah", "L'échec peut sembler décourageant, mais cette citation nous encourage à garder la foi en nous-mêmes et à continuer à travailler dur pour atteindre nos objectifs.", '2023-01-29 10:36:02'),
(901, 717, "CosmicCactus", "Cette citation nous rappelle que l'échec est un élément naturel de tout processus créatif et qu'il peut être utilisé comme source d'inspiration pour nous aider à innover.", '2023-01-03 08:32:05'),
(902, 717, "EnchantedElk", "J'aime cette citation car elle nous encourage à ne pas se laisser abattre par l'échec, mais plutôt à le voir comme une occasion de nous améliorer.", '2023-03-30 09:57:21'),
(907, 743, "RadiantRaccoon", "Cette citation nous rappelle que chaque échec est une occasion de réévaluer nos priorités et de nous concentrer sur ce qui est vraiment important pour nous.", '2023-04-07 18:13:55'),
(910, 743, "JadeJaguar", "L'échec peut sembler insurmontable, mais cette citation nous rappelle que nous avons la capacité de surmonter nos obstacles et d'atteindre nos objectifs.", '2023-03-14 03:05:23'),
(940, 743, "StarrySwan", "Cette citation nous encourage à ne pas avoir peur de l'échec et à continuer à travailler dur pour réaliser notre potentiel.", '2023-03-15 12:26:40'),
(981, 691, "ElectricEagle", "J'aime cette citation car elle nous rappelle que même les échecs les plus douloureux peuvent être surmontés avec le temps et la persévérance.", '2023-03-09 13:53:26'),
(993, 724, "FieryFox", "J'aime cette citation car elle nous rappelle que même les échecs les plus douloureux peuvent être surmontés avec le temps et la persévérance.", '2023-01-09 19:26:22');