DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users(
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    bio TEXT,
    PRIMARY KEY(username),
    UNIQUE KEY (email) );

INSERT INTO Users
VALUES
("GalacticSailor", "bvhzawtk@nfsxp.com", "Oliver", "Hernandez", "Amoureux des citations et des mots inspirants."),
("EnigmaticKraken", "dfjksrty@hznuf.net", "Jackson", "Smith", "À la recherche de la beauté dans les mots."),
("EmeraldDragonfly", "gwnqmxvmp@shuks.com", "Emma", "Johnson", "Diffuseur de positivité à travers les citations."),
("BlissfulGnome", "zjvucrpl@ytnxu.net", "Liam", "Williams", "Collectionneur de citations inspirantes."),
("SapphireJazz", "bxzwfaun@zguxo.org", "Ava", "Brown", "Partageur de sagesse en petites doses."),
("MysticWombat", "jxfkhsdm@vtdbo.com", "Noah", "Jones", "Donneur d'espoir grâce aux mots."),
("ElectricPenguin", "qomzylrx@juzen.net", "Sophia", "Garcia", "Écrivain de phrases qui résonnent."),
("CosmicChameleon", "ntbgcipo@qikom.org", "Ethan", "Miller", "Créateur de citations pour les jours sombres."),
("VelvetPhoenix", "lqakmzdv@cnfbx.com", "Isabella", "Davis", "Étudiant de la vie à travers les mots."),
("RadiantLynx", "ycnwufvp@ivxek.net", "Mason", "Rodriguez", "Ambassadeur de la motivation à travers les citations."),
("LunarSphinx", "rypohqbm@lqeyu.org", "Mia", "Martinez", "Évangéliste de la pensée positive."),
("CrimsonCobra", "swndjyra@pkhfa.net", "Charlotte", "Lopez", "Chasseur de belles phrases et de bons mots."),
("CelestialRaven", "gzlakdco@oeyur.org", "Aiden", "Perez", "Fournisseur de sagesse en ligne."),
("SilverStallion", "cxvmdnqw@lybco.com", "Amelia", "Gonzalez", "Rêveur et créateur de citations inspirantes."),
("MysticMoose", "uivxepab@wymkg.org", "Harper", "Wilson", "Poète moderne en quête de sens."),
("FieryFalcon", "ojhfnqwp@esryc.com", "Lucas", "Anderson", "Producteur de citations pour les moments difficiles."),
("OceanicOctopus", "tkrazebn@qvpix.net", "Evelyn", "Thomas", "Faiseur de rêves grâce aux mots."),
("CrimsonCheetah", "ywqixpmz@ujoft.org", "Logan", "Jackson", "Éveilleur d'esprit grâce aux citations."),
("CosmicCactus", "ktyjcxdf@rmdsw.com", "Abigail", "White", "Trouveur de lumière dans les ténèbres grâce aux mots."),
("EnchantedElk", "vwrhgoul@xkzqb.net", "Caleb", "Harris", "Bâtisseur de ponts avec des mots."),
("RadiantRaccoon", "eczyptna@fmvjo.org", "Emily", "Martin", "Créateur de citations pour les âmes perdues."),
("JadeJaguar", "nixogqbs@dyvpk.com", "Benjamin", "Thompson", "Chercheur de vérité en parcourant les citations."),
("StarrySwan", "bmyztqjx@lsgeo.net", "Elizabeth", "Moore", "Éducateur de l'âme à travers les citations."),
("ElectricEagle", "sqazudcw@riupq.org", "Michael", "Robinson", "Artisan de la langue à travers les citations."),
("FieryFox", "lgebxkfh@vynco.com", "Grace", "Walker", "Partageur de citations pour illuminer votre journée."),
("RadiantRoadrunner", "udyrmqvn@ofwsm.com", "William", "Baker", "Explorateur de l'âme humaine à travers les mots."),
("MysticMermaid", "bgxiojtk@ufolr.net", "Olivia", "Carter", "Écrivain de la vie à travers les citations."),
("CosmicCoyote", "qacblnmo@yurkh.org", "Elijah", "Clark", "Créateur de citations pour les coeurs brisés."),
("CelestialSiren", "vrfwskpd@hgojq.com", "Lily", "Collins", "Faiseur de rêves grâce aux mots."),
("SapphireStork", "ijxthuwe@cpzsf.net", "Alexander", "Cooper", "Trouveur de beauté dans les mots simples."),
("EnchantedEagle2", "qpfnrgmc@lzykt.org", "Chloe", "Edwards", "Collectionneur de citations pour égayer votre journée."),
("RadiantRabbit", "vlkuymhx@jtsba.com", "James", "Evans", "Pourfendeur de la négativité grâce aux citations."),
("LunarLion", "ndyfsizg@oxemp.net", "Madison", "Foster", "Bâtisseur de ponts entre les cultures grâce aux mots."),
("VelvetVixen", "xmyuvzbp@kogrl.org", "Benjamin", "Gray", "Amoureux des mots qui dansent sur la page."),
("FieryFeline", "ebhwtofn@adzjy.com", "Emma", "Green", "Éducateur de la vie à travers les citations."),
("ElectricElephant2", "zjbnltfq@ewqri.net", "Samuel", "Hall", "Partageur de citations pour élever votre esprit."),
("OceanicOstrich", "ktcdwyvu@jnpyx.org", "Ava", "Hill", "Éveilleur de conscience grâce aux mots."),
("EnigmaticEmu", "pmqakzlj@vscud.com", "Henry", "Hughes", "Explorateur de l'imaginaire grâce aux citations."),
("CrimsonCrocodile", "dvyhsgex@rxfkb.net", "Harper", "James", "Poète des émotions et des sentiments."),
("JadeJellyfish", "cuqgimtz@bdsyj.org", "Daniel", "Kelly", "Créateur de citations pour les amoureux."),
("MysticMongoose", "hnvjowry@fmuop.com", "Isabella", "King", "Défenseur de la tolérance grâce aux mots."),
("GalacticGazelle", "lbwmxzks@ieton.net", "Matthew", "Lee", "Chercheur de la beauté cachée dans les mots."),
("SilverSquirrel", "sxfnoyui@pkblc.org", "Mia", "Lewis", "Partageur de citations pour les esprits libres."),
("CelestialCrane", "eklpbgaj@jzvru.com", "Joseph", "Mitchell", "Éveilleur de la créativité grâce aux mots."),
("CosmicCamel", "rsiwhtdc@gyfne.net", "Scarlett", "Nelson", "Semeur d'espoir à travers les citations."),
("EnchantedEchidna", "jtyplfnu@azkoq.org", "David", "Parker", "Chercheur de lumière dans les moments sombres."),
("FieryFerret", "gmhqkxvo@nwbcu.com", "Aria", "Powell", "Créateur de citations pour les épreuves de la vie."),
("StarryShark", "obqlvize@tmdfp.net", "Gabriel", "Ramirez", "Éducateur de l'âme à travers les mots."),
("EmeraldElk", "yczjgtak@ulqir.org", "Victoria", "Ross", "Producteur de citations pour les moments de réflexion."),
("MysticManta", "xtlhmrbn@vpkoe.com", "Christopher", "Sanchez", "Artisan de la parole qui fait vibrer l'âme."),
("CelestialCaterpillar", "taydmxfp@jkuhs.com", "Joshua", "Scott", "Citations pour les âmes sensibles et les esprits créatifs."),
("RadiantRaven", "qezrywsa@hgopc.net", "Isabelle", "Simmons", "Des mots qui inspirent, des phrases qui touchent l'âme."),
("CosmicCobra", "ukjoihnb@lsamu.org", "Nicholas", "Taylor", "Créateur de citations pour les rêveurs et les chercheurs."),
("SapphireSeahorse", "wnkjgsfv@bdtyx.com", "Ella", "Turner", "Artisan des mots, éveilleur de conscience."),
("MysticMonkey", "yivlqbzo@kfumd.net", "Andrew", "Walker", "Citations pour les amoureux des livres et des belles phrases."),
("EnchantedEel", "fgwptaxc@isjor.org", "Avery", "Ward", "Des mots pour guérir, des phrases pour éclairer le chemin."),
("ElectricElk", "cebqnxry@udapl.com", "Nathan", "Watson", "Écrivain passionné, collectionneur de pensées inspirantes."),
("LunarLlama", "eumvkslj@pqtzc.net", "Sofia", "West", "Citations pour les âmes libres et les esprits audacieux."),
("VelvetVampire", "pwndixog@vfkru.org", "Ryan", "Wood", "Des mots pour apaiser l'âme, des phrases pour stimuler l'esprit."),
("FieryFawn", "ajcbhztk@qgxsw.com", "Penelope", "Young", "Créateur de phrases qui résonnent, de pensées qui inspirent."),
("OceanicOtter", "sfqwpnru@jzoim.net", "Daniel", "Adams", "Citations pour les amoureux de la poésie et de la beauté."),
("EnigmaticEagle", "dkoxmtyv@ryiep.org", "Addison", "Bailey", "Des mots pour explorer, des phrases pour découvrir."),
("CrimsonCormorant", "gmyhxfzn@uipqw.com", "Zachary", "Bennett", "Écrivain passionné, collectionneur de perles de sagesse."),
("JadeJester", "yojtrsil@beavk.net", "Aubrey", "Bishop", "Citations pour les chercheurs de vérité et les âmes en quête de sens."),
("MysticMarmot", "tkopdrbu@nlhfm.org", "Caleb", "Brooks", "Des mots pour célébrer la vie, des phrases pour illuminer l'esprit."),
("GalacticGiraffe", "fxjvzeqw@aswko.com", "Audrey", "Butler", "Créateur de citations pour les rêveurs et les voyageurs."),
("RadiantRaccoon2", "bzqckysn@tguxd.net", "Owen", "Campbell", "Citations pour les amoureux de la nature et de la beauté sauvage."),
("SilverSnake", "xjupmwgo@vrndj.org", "Savannah", "Chavez", "Des mots pour réconforter, des phrases pour inspirer."),
("CosmicCivet", "oqlyseth@dfcix.com", "Evan", "Coleman", "Écrivain passionné, collectionneur de trésors littéraires."),
("EnchantedEagle", "jsmviurt@czkbq.net", "Nora", "Cook", "Citations pour les âmes poétiques et les esprits épris de liberté."),
("FieryFalconer", "ukqfjhow@nbyur.org", "Dylan", "Crawford", "Des mots pour guider, des phrases pour éveiller."),
("StarryStingray", "tpyrkbxz@eaocp.com", "Leah", "Diaz", "Créateur de phrases qui font écho, de pensées qui résonnent."),
("EmeraldEchidna", "qziugjfn@lwvkm.net", "Luke", "Douglas", "Citations pour les amoureux de la méditation et de la pleine conscience."),
("MysticMoth", "eokaxpry@sjbhq.org", "Zoey", "Ellis", "Des mots pour inspirer l'amour, des phrases pour cultiver la paix."),
("ElectricElephant", "zjubnvwl@cympg.com", "Anthony", "Flores", "Écrivain passionné, collectionneur de joyaux de la littérature universelle."),
("CelestialCentipede", "zgxvqjbm@rtpsi.com", "Oliver", "Franklin", "Citations pour les rêveurs et les audacieux."),
("CosmicCougar", "hjumyxfk@zkpfn.net", "Amelia", "Gibson", "Des mots pour éclairer l'esprit, des phrases pour guérir l'âme."),
("SapphireSparrow", "eibynqoa@cvuhr.org", "William", "Graham", "Écrivain en herbe, créateur de pensées inspirantes."),
("MysticMandrill", "ktpavzsr@bxlyg.com", "Elizabeth", "Guerrero", "Citations pour les amoureux des émotions fortes et des expériences intenses."),
("EnchantedElkhound", "dgmpcljw@owkar.net", "Samuel", "Hamilton", "Des mots pour encourager, des phrases pour motiver."),
("RadiantRat", "ysjukrbn@mhlnf.org", "Grace", "Harper", "Poète de l'âme, explorateur des sentiments."),
("ElectricEchidna", "xvwnefgt@zkyua.com", "Matthew", "Hayes", "Citations pour les passionnés de la vie et des découvertes."),
("LunarLemming", "urhqkgop@lfmec.net", "Harper", "Holland", "Des mots pour inspirer la créativité, des phrases pour susciter l'imagination."),
("VelvetVole", "vnopbcti@yxiws.org", "Christopher", "Hopkins", "Écrivain passionné, éveilleur de conscience."),
("FieryFrigatebird", "qkrbltad@jmwpy.com", "Madison", "Howell", "Citations pour les amoureux de la musique et de l'art."),
("OceanicOcelot", "eadzyjsn@wqfcu.net", "Isaac", "Hudson", "Des mots pour célébrer la beauté, des phrases pour apprécier la simplicité."),
("EnigmaticElk", "suqgwhxv@nkboe.org", "Avery", "Jenkins", "Collectionneur de citations inspirantes, éditeur de pensées positives."),
("CrimsonCuckoo", "lykbjvci@pfota.com", "Alexander", "Kim", "Citations pour les âmes romantiques et les esprits philosophiques."),
("JadeJay", "ndzimxwe@ruvjs.net", "Scarlett", "Lane", "Des mots pour encourager la persévérance, des phrases pour renforcer la détermination."),
("MysticMole", "tpvjgohf@eisrc.org", "Ethan", "Larson", "Écrivain en devenir, créateur de belles phrases."),
("GalacticGorilla", "fbajmuqz@cxkpl.com", "Isla", "Mason", "Citations pour les amoureux de la culture et des traditions."),
("RadiantRhino", "hqvnukpy@otbmz.net", "Lucas", "Matthews", "Des mots pour apporter la paix, des phrases pour encourager l'harmonie."),
("SilverSwan", "mniotxru@jlavw.org", "Sofia", "Moreno", "Poète de l'instant présent, explorateur de la vie intérieure."),
("CosmicChinchilla", "oxcypzgs@uqfab.com", "David", "Murray", "Citations pour les passionnés de l'aventure et de l'inconnu."),
("EnchantedEmperor", "izbjmhta@wsnry.net", "Abigail", "Nguyen", "Des mots pour stimuler la créativité, des phrases pour encourager l'expression personnelle."),
("FieryFlamingo", "ytlcpgxf@edmqi.org", "Joseph", "Owens", "Écrivain passionné, collectionneur de pensées inspirantes."),
("StarryScorpion", "xavkbwqn@hpgot.com", "Aria", "Pierce", "Citations pour les amoureux de la nature et de l'environnement."),
("EmeraldEagle", "rdlvfecz@ujkby.net", "Benjamin", "Reid", "Des mots pour apporter la joie, des phrases pour inspirer le bonheur."),
("MysticMosquito", "jymqxuos@oitcs.org", "Eleanor", "Rivera", "Écrivain en quête de vérité, créateur de pensées profondes."),
("ElectricEagleRay", "ujsoyzrp@gvkwl.com", "Michael", "Schmidt", "Citations pour les âmes généreuses et les esprits bienveillants.");
